### ISSUE TITLE
Reset les couleurs

### ISSUE THREAD

**Issue by Holosmos** [viki53/Nick#2]
Pouvoir reset par une commande simple toutes les couleurs ou alors celle d'un pseudo en particulier.

**Comment by viki53** [comment]
Précisions : créer un commande `/color` qui puisse prendre en paramètre un pseudo.

Si pseudo : on reset la couleur du pseudo.
Sans pseudo : on reset les couleurs de tous les users du channel

**Comment by viki53** [comment]
Géré dans le commit c1066e476b465cd71b3211a47010ba5351833b02
