### ISSUE TITLE
Lister les utilisateurs en lignes

### ISSUE THREAD

**Issue by Lramelot** [viki53/Nick#5]
Pouvoir choisir l'ordre d'affichages des utilisateurs, par défaut les afficher par ordre de grade et puis ordre alphabétique

**Comment by viki53** [comment]
Fait : commits 165026f49ced9a7b6192187a8276ee0f750c1122 & bb92775de24eec3e2b6c2c339e41b5130e495409

Si ça convient, je ferme un peu plus tard ;)

**Comment by Lramelot** [comment]
Petit problème au niveau de l'ordre des droits, Kiwi apparait avant vhf, ça devrait être l'ordre inverse. http://i.gyazo.com/d936d4105218e44f68175ae868b703d6.png

**Comment by viki53** [comment]
C'est bien possible', je ne maîtrise pas vraiment l'ordre des droits du coup j'ai fait comme j'ai pu… ^^

Tu peux regarder [ligne 105](https://github.com/viki53/Nick/blob/master/js/nick-v1.js#L105) pour voir comment je dois ré-organiser le tableau, c'est là-dessus que se base l'ordre. ;)
